# Generated by Django 5.2.3 on 2025-06-23 20:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("quantity", models.CharField(max_length=50)),
                ("instructions", models.TextField()),
                (
                    "image",
                    models.ImageField(default="img/default.png", upload_to="img/"),
                ),
                ("likes", models.IntegerField(default=0)),
                ("vegan", models.BooleanField(default=False)),
                ("published", models.DateTimeField(auto_now_add=True)),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le mot de passe doit contenir au moins 8 caractères, dont au moins un chiffre, une minuscule et une majuscule",
                                regex="^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$",
                            )
                        ],
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.category",
                    ),
                ),
            ],
        ),
    ]
